name: Zig CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test Modules
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
      - name: Cache BoringSSL Build
        uses: actions/cache@v3
        with:
          path: libs/boringssl/build
          key: boringssl-${{ hashFiles('libs/boringssl/**') }}
          restore-keys: |
            boringssl-
      - run: zig build test --summary all
