name: Zig CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test Modules
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Zig
        uses: mlugg/setup-zig@v1
      
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake unzip curl

      - name: Install BoringSSL
        run: make install
      
      - name: Run Tests
        run: make test
