name: Zig CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test Modules
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
      - run: |
          # Verify the presence of BoringSSL prebuilt files
          ls -la libs/boringssl

          # Run Zig tests
          zig build test --summary all
